INSERT INTO users (
    user_id,
    member_role,
    name,
    phone_number,
    social_email,
    social_type,
    user_key,
    birth_date,
    address,
    credit_point,
    entertainer_id,
    represent_account_id,
    created_at,
    modified_at
) VALUES (
             1,
             'GENERAL',
             '권민채',
             '010-0000-0000',
             'minchae075@naver.com',
             'SSAFY',
             'bc528a94-b677-47a8-9d61-a00b30f2acac',
             '2000-01-01 00:00:00',
             'Example Address',
             '0',
             NULL,
             NULL,
             NOW(),
             NOW()
         );