services:
  ai-server-1:
    container_name: ai-server-1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul

  ai-server-2:
    container_name: ai-server-2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul

  ai-server-3:
    container_name: ai-server-3
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul