spring:
  security:
    oauth2:
      client:
        registration:
          ssafy:
            client-id: ${OAUTH_ID:test}
            client-secret: ${OAUTH_SECRET:test}
            client-name: ssafy-login
            client-authentication-method: client_secret_post
            redirect-uri: ${OAUTH_REDIRECT_URI:test}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
        provider:
          ssafy:
            authorization-uri: ${OAUTH_AUTHORIZATION_URI:test}
            token-uri: ${OAUTH_TOKEN_URI:test}
            user-info-uri: ${OAUTH_USER_INFO_URI:test}
            user-name-attribute: id