lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames: [
  "java.lang:type=Memory",
  "java.lang:type=GarbageCollector,name=*",
  "java.lang:type=Threading",
  "java.lang:type=OperatingSystem",
  "java.lang:type=ClassLoading",
  "java.lang:type=Runtime"
]
rules:
  - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(\w+)'
    name: jvm_memory_heap_$1
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(\w+)'
    name: jvm_memory_nonheap_$1
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=GarbageCollector, name=(.+)><>CollectionCount'
    name: jvm_gc_collection_count
    help: 'Garbage collection count'
    type: COUNTER
    labels:
      name: $1
  - pattern: 'java.lang<type=GarbageCollector, name=(.+)><>CollectionTime'
    name: jvm_gc_collection_time_seconds
    help: 'Garbage collection time'
    type: COUNTER
    labels:
      name: $1
  - pattern: 'java.lang<type=Threading><>ThreadCount'
    name: jvm_threads_live
    type: GAUGE
  - pattern: 'java.lang<type=OperatingSystem><>ProcessCpuLoad'
    name: process_cpu_usage
    type: GAUGE
  - pattern: 'java.lang<type=OperatingSystem><>SystemCpuLoad'
    name: system_cpu_usage
    type: GAUGE
  - pattern: 'java.lang<type=ClassLoading><>LoadedClassCount'
    name: jvm_classes_loaded
    type: GAUGE